import Head from "next/head";
import fs from "fs/promises";
import path from "path";
import Link from "next/link";

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {props.products.map((product) => (
          <li key={product.id}>
            <Link href={`/product/${product.id}`}>{product.title}</Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

export async function getStaticProps(context) {
  const filePath = path.join(process.cwd(), "data", "dummy-backend.json");
  const jsonData = await fs.readFile(filePath);
  const data = JSON.parse(jsonData);

  // THIS WILL RETURN A 404 PAGE IF THERE IS NOT CONTENT IN THE PRODUCT
  if (data.products.length === 0) {
    return {
      notFound: true,
    };
  }

  // THIS WILL REDIRECT TO ANOTHER PAGE IF THERE IS NO DATA
  if (!data) {
    return {
      redirect: {
        // YOU CAN PUT THE PATH TO THE PAGE YOU WANT TO REDIRECT TO
        destination: "/no-data",
      },
    };
  }

  return {
    props: {
      products: data.products,
    },
    revalidate: 10,
  };
}
